language: python
python: "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=py34

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmpfr4
  - sudo apt-get install -y libmpc
  - sudo apt-get install -y libgmp-dev
  - sudo apt-get install -y libmpfr-dev
  - sudo apt-get install -y libmpc-dev

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
