language: python
python: "2.7"

env:
  - TOX_ENV=py27

install:
  - pip install -U pytest
  - pip install -U tox
  - pip install -U coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
