language: python

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
 - pip install -U tox
 - sudo apt-get -qq install libgmp-dev
 - pip install -e .

script:
 - tox -e $TOX_ENV
