language: python
python: "2.7"

env:
  - TOX_ENV=py27

install:
  - pip install -U tox

python:
  - "2.7"

install:
 - sudo apt-get -qq install libgmp-dev
 - pip install -e .

script:
 - tox -e $TOX_ENV
